### ISSUE TITLE
Add an option to delete PVCs while uninstalling the Helm Chart

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-helm-chart#134]
While running tests on GKE with Fallout we found out that disks are not released even by deleting the GKE cluster.
This is because the PVC created by the Helm Chart are not deleted when uninstalling the chart.

It would be great to have an option to automatically delete the PVCs

**Comment by guyboltonking** [comment]
I think this issue should be "Add an option to change the reclaimPolicy on the StorageClasses to Delete".

The issue we have in fallout is that when we destroy a cluster that has this helm chart installed PVCs are leaked because there are several underlying StorageClass definitions that use `reclaimPolicy: Retain`, with no way of specifying anything else in `values.yaml`.  There should be a way of specifying the reclaimPolicy; also, should we consider whether a default of `Retain` is appropriate?

**Comment by eolivelli** [comment]
@michaeljmarshall what do you think ?
do you think we can do what @guyboltonking is suggesting and cut a release soon ?

**Comment by lhotari** [comment]
@guyboltonking Please review #137 . That adds support for setting the reclaimPolicy. 

Are you aware of Helm issue https://github.com/helm/helm/issues/5156 ? Helm won't delete PVCs even when reclaimPolicy==Delete. However there's [a workaround](https://github.com/helm/helm/issues/5156#issuecomment-812695838). 

Please let us know if #137 suites your needs.

**Comment by guyboltonking** [comment]
> Are you aware of Helm issue helm/helm#5156 ? Helm won't delete PVCs even when reclaimPolicy==Delete.

Yes, I saw that; it's not the same as this issue though, as _that_ issue is about what happens on `helm uninstall`, and this is about what happens to disks after destroying a GKE cluster.  The issue we have is that when a GKE cluster is destroyed, PV backing disks in GCE are not deleted.  This can happen when:
* A PVC is not deleted before the cluster is destroyed; this leaves the backing disk active (I'm going to address this in fallout by aggressively tidying up backing disks after the cluster is destroyed);
* A PVC _is_ deleted, but the associated StorageClass had `reclaimPolicy: Retain` (which is what I _think_ this issue/ #137 is addressing).

Thanks for getting to #137 so quickly; I think this can be closed now (do you mind if I update the title?)

**Comment by lhotari** [comment]
Thanks for confirming @guyboltonking
